version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: call_forwarding
    container_name: call_forwarding
    ports:
      - "8080:8080"

  harperdb:
    image: harperdb/harperdb:latest
    container_name: harperdb
    environment:
      - HDB_ADMIN_USERNAME=${DB_USERNAME}
      - HDB_ADMIN_PASSWORD=${DB_PASSWORD}
    ports:
      - "9925:9925"