name: Build workflow
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: call-forwarding

on:
  pull_request:
    branches:
      - master
    types: 
      - opened
  push:
    branches: 
      - master

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: print all environment variables
        run: env
        

      - name: Checkout code
        uses: actions/checkout@v4

      - name: run build script
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event.pull_request.merged == true }}
        run: ./my_build.sh

