name: Build workflow
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: call-forwarding

on:
  pull_request:

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: print all environment variables
        run: env

      - name: install golang
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      
      - name: check go version
        run: go env

      - name: Checkout code
        uses: actions/checkout@v4

      - name: run static check script
        run: ./scripts/staticchecks.sh

      - name: run build script
        if: ${{ github.event.pull_request.merged == true }}
        run: ./scripts/my_build.sh

